### PR TITLE
Fix `sv_pure_bypass_8`

### LINKED ISSUE #39: The bug still works for me
https://www.youtube.com/watch?v=AMVHp8a-vz0

### PR DESCRIPTION
**Pull request by szmarczak**
https://github.com/szmarczak/csgo_bugs/tree/lol/sv_pure_bypass_8

Fixes #39 

Enables wallhacks on more maps.

Thanks to @Billar42

### CODE REVIEW

File: sv_pure_bypass_8/wallhack.js [hunk 1]
```diff
@@ -227,49 +255,56 @@ const findWallhackProps = buffer => {
...
-
-			while (buffer[index] in current) {
-				current = current[buffer[index++]];
-
-				if (Object.keys(current).length === 0) {
-					return {
-						startIndex: start,
-						endIndex: index
-					};
+		for (let index = start; index < bufferLength; index++) {
```
Comment (szmarczak) [inline sv_pure_bypass_8/wallhack.js:280]: This search algorithm is more efficient. Boosts from ~800ms to ~500ms.

File: sv_pure_bypass_8/README.md [hunk 2]
```diff
@@ -40,8 +40,27 @@ then recompile with Visual Studio.
...
+
+* Dust: none
+* Train: none
+* Anubis: none
+* Ancient: none
 
 ### Credits
 
 * [@szmarczak](https://github.com/szmarczak) for discovering the bug.
+* [@Billar42](https://github.com/Billar42) for noticing that replacing other VPK files will enable wallhacks on more maps.
```
Comment (szmarczak) [inline sv_pure_bypass_8/README.md:66]: The previous `mirror.exe` located in this directory was bypassing only `pak01_008.vpk`. This one bypasses all file locks inside the CSGO directory.

**Comment by szmarczak** [comment]
Do not merge yet I just got the info that `R_RedownloadAllLightmaps took` is not displayed for some people

**Comment by szmarczak** [comment]
Ok it should work for everyone now
